# refer to the DVC documentation


stages:
  data_ingestion:
    cmd: python src/CNN_Classifier/pipeline/stage_01_data_ingestion.py
    # will run the stage_01_data_ingestion.py script
    deps:
      - src/CNN_Classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
      # file depends on its own file and the config.yaml file due to the data ingestion configuration
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image
      # outputs the kidney-ct-scan-image folder to the artifacts/data_ingestion folder


  prepare_base_model:
    cmd: python src/CNN_Classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/CNN_Classifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
      # parameters used during the prepare base model stage
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/CNN_Classifier/pipeline/stage_03_model_training.py
    deps:
      - src/CNN_Classifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      # also depends on the kidney-ct-scan-image data
      - artifacts/prepare_base_model
      # needs prepare_base_model to train the model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/CNN_Classifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/CNN_Classifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false